M48
; DRILL file {KiCad (7.0.0)} date Mon May 15 16:57:05 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-15T16:57:05+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0472
%
G90
G05
T1
X4.9896Y-4.0561
X5.2171Y-4.0561
X5.5739Y-4.0562
X5.8014Y-4.0562
T2
X5.7917Y-3.298
T3
X4.9965Y-3.298
T0
M30
